# Numpy

In [1]:
import numpy as np

In [3]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
print(a[1], a[2])

[5 6 7 8] [ 9 10 11 12]


In [12]:
print(a[1,0])

5


In [13]:
# Range

a.ndim

2

In [14]:
a.shape

(3, 4)

In [22]:
print(np.ones(2)) #Untuk menampilkan value 1
print(np.zeros(2)) #Untuk menampilkan value 0

[1. 1.]
[0. 0.]


In [26]:
ones1 = np.ones((6,2))
print(ones1)
print('')
form1 = ((4,5))
ones2 = np.ones(form1)
print(ones2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [28]:
ones3 = np.ones((2,3,4))
ones3

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [29]:
numbers = np.full((2,4),7)
numbers

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [30]:
numbers = np.full((2,4),7, dtype='float')
numbers

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [31]:
empty_arr = np.empty(6)
empty_arr

array([0., 0., 0., 0., 0., 0.])

In [40]:
print(np.arange(7))
print(np.arange(0, 15, 3)) #(start, max, kelipatan)

[0 1 2 3 4 5 6]
[ 0  3  6  9 12]


In [43]:
np.arange(2,6) #start and length array

array([2, 3, 4, 5])

In [45]:
print(np.arange(10, 0, -2))

[10  8  6  4  2]


In [46]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr


array([1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
arr_new = np.append(arr, [1,15] )
arr_new


array([ 1,  2,  3,  4,  5,  6,  7,  8,  1, 15])

In [49]:
arr_new.shape
arr


array([1, 2, 3, 4, 5, 6, 7, 8])

In [50]:
np.delete(arr, 6)


array([1, 2, 3, 4, 5, 6, 8])

In [51]:
arr2d = np.array([[9, 18, 3, 7], [2, 1, 10, 34], [51, 0, 8, 13]])
arr2d


array([[ 9, 18,  3,  7],
       [ 2,  1, 10, 34],
       [51,  0,  8, 13]])

In [53]:
# np.sort(arr2d, axis=0)

np.sort(arr2d, axis=1)


array([[ 3,  7,  9, 18],
       [ 1,  2, 10, 34],
       [ 0,  8, 13, 51]])

In [54]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
 
                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]],
                       
                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]]
                        ])
 
print(array_example)


[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [55]:
array_example.ndim

3

In [56]:
array_example.shape


(3, 2, 4)

In [57]:

array_example.size


24

In [59]:
array_example.dtype 

dtype('int32')

In [60]:
array_example.itemsize


4

In [61]:
# array_example.astype('int16')
array_example = np.array([[[0, 1, 2, 3],
                        [4, 5, 6, 7]],

                        [[0, 1, 2, 3],
                        [4, 5, 6, 7]],
                   
                        [[0, 1, 2, 3],
                        [4, 5, 6, 7]]
                        ], dtype = 'int16')
array_example.dtype


dtype('int16')

In [62]:
array_example.itemsize

2

In [68]:
ones4 = np.ones((3,4))
ones4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [71]:
ones4.reshape(6,2)


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [76]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [77]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [78]:
c = a.reshape(2,3,1)
c

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [79]:
a = np.arange(18)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [80]:
d = a.reshape(3,3,2)
print(d)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]


In [81]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)
print(a)


(6,)
[1 2 3 4 5 6]


In [83]:
#Kamu juga dapat menggunakan np.newaxis untuk menambahkan axis
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [84]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [85]:
# for a column vector, You can insert an axis along the second dimension
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)


(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [87]:
data = np.array([1,2,3,4])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[:3])

[1 2 3 4]
1
2
[1 2]
[2 3 4]
[1 2 3]


In [88]:
# You can select elements that are divisible by 2

divisible_by_2 = (a%2 == 0)
print(a[divisible_by_2])

divisible_by_3= (a%3 == 0)
print(a[divisible_by_3])



[2 4 6]
[3 6]


In [89]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [90]:
multiple_conditions = ((a > 2) & (a < 11))
a[multiple_conditions]


array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
random_af = np.random.rand(3,5)
print(random_af)
print(random_af.dtype)


[[0.86168336 0.13062822 0.64589841 0.66732873 0.36052485]
 [0.24528541 0.40080136 0.98716068 0.60338386 0.34141337]
 [0.2979108  0.54779236 0.25631918 0.16841961 0.84911065]]
float64


In [92]:
random_af = np.random.rand(3)
print(random_af)


[0.58004386 0.88163686 0.89866421]


# Working with Math Formulas

In [ ]:
error = (1/n) * np.sum(np.square(observed - prediction))